name: Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: cargo-check
      run: cargo check
    - name: cargo-Clippy
      run: cargo clippy
    - name: cargo-fmt
      run: cargo fmt --all --check
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: 'app/package-lock.json'
      - name: Install dependencies
        working-directory: app
        run: npm install
      - name: lint
        working-directory: app
        run: npm run lint
        